local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', builtin.find_files, {})
vim.keymap.set('n', '<leader>b', builtin.buffers, {})
vim.keymap.set('n', '<leader>s', builtin.live_grep, {})
vim.keymap.set('n', '<leader>ds', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>ws', builtin.lsp_dynamic_workspace_symbols, {})
-- vim.keymap.set('n', '<leader>g', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>s', function()
--     builtin.grep_string({ search = vim.fn.input("Grep > ") })
-- end)
